name: Deploy Frontend

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths:
      - 'frontend/**'  # Run only if there are changes in the frontend folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: List files
        run: ls -la frontend  # List files to ensure the frontend directory contains the Dockerfile
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set version tag
        id: vars
        run: echo "VERSION_TAG=harith47/platform:${GITHUB_SHA::7}-frontend" >> $GITHUB_ENV

      - name: Build & Push Docker image
        run: docker buildx build --platform linux/amd64 -f frontend/Dockerfile -t ${{ env.VERSION_TAG }} --push frontend

      - name: List Docker images
        run: docker images  # Debugging step to confirm image exists

      - name: Trigger Deployment Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.REPO_PAT }}" \
          https://api.github.com/repos/harith-bechkam/minikube_deployments/actions/workflows/frontend.yml/dispatches \
          -d '{"ref":"master", "inputs": {"version_tag": "${{ env.VERSION_TAG }}", "commit_message": "${{ github.event.head_commit.message }}"}}'
